# Generated by Django 3.2.5 on 2023-03-31 05:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='at_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_tit_001', models.CharField(default='標題', max_length=1000, verbose_name='活動名稱')),
                ('at_ph_001', models.CharField(default='活動圖照', max_length=1000, verbose_name='照片連結')),
                ('at_con_001', ckeditor.fields.RichTextField(blank=True, default='活動內容', max_length=1000, null=True, verbose_name='活動內容')),
            ],
            options={
                'verbose_name': '活動專區',
                'verbose_name_plural': '活動專區',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='castle_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castle_ph_001', models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '古堡婚紗',
                'verbose_name_plural': '古堡婚紗',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Cp_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_ph_001', models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '攝影作品-情侶寫真',
                'verbose_name_plural': '攝影作品-情侶寫真',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='family_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam_001', models.CharField(default='', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '全家福',
                'verbose_name_plural': '全家福',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Index_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_ph_010', models.CharField(max_length=1000, null=True, verbose_name='左直')),
                ('mid_ph_011', models.CharField(max_length=1000, null=True, verbose_name='右上')),
                ('mid_ph_012', models.CharField(max_length=1000, null=True, verbose_name='右下')),
                ('mid_001', models.CharField(max_length=10, verbose_name='標題名稱')),
                ('mid_ph_001', models.CharField(max_length=1000, null=True, verbose_name='照片連結')),
                ('mid_txt_001', models.TextField(max_length=100, verbose_name='內容')),
                ('mid_002', models.CharField(max_length=10, verbose_name='標題名稱')),
                ('mid_ph_002', models.CharField(max_length=1000, null=True, verbose_name='照片連結')),
                ('mid_txt_002', models.TextField(max_length=100, verbose_name='內容')),
                ('mid_003', models.CharField(max_length=10, verbose_name='標題名稱')),
                ('mid_ph_003', models.CharField(max_length=1000, null=True, verbose_name='照片連結')),
                ('mid_txt_003', models.TextField(max_length=100, verbose_name='內容')),
                ('mid_004', models.CharField(max_length=10, verbose_name='標題名稱')),
                ('mid_txt_004', models.TextField(max_length=100, verbose_name='內容')),
                ('mid_ph_004', models.CharField(max_length=1000, null=True, verbose_name='照片連結')),
                ('mid_005', models.CharField(max_length=10, verbose_name='標題名稱')),
                ('mid_txt_005', models.TextField(max_length=100, verbose_name='內容')),
                ('mid_ph_005', models.CharField(max_length=1000, null=True, verbose_name='照片連結')),
                ('mid_006', models.CharField(max_length=10, verbose_name='標題名稱')),
                ('mid_txt_006', models.TextField(max_length=100, verbose_name='內容')),
                ('mid_ph_006', models.CharField(max_length=1000, null=True, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '首頁',
                'verbose_name_plural': '首頁',
            },
        ),
        migrations.CreateModel(
            name='location_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_ph_001', models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '拍攝景點',
                'verbose_name_plural': '拍攝景點',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'web_member',
            },
        ),
        migrations.CreateModel(
            name='os_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_tit_001', models.CharField(default='標題', max_length=1000, verbose_name='海外標題')),
                ('os_con_001', ckeditor.fields.RichTextField(blank=True, default='內容', max_length=1000, null=True, verbose_name='海外內容')),
            ],
            options={
                'verbose_name': '海外專區',
                'verbose_name_plural': '海外專區',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pf_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_ph_001', models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '攝影作品-專業形象照片',
                'verbose_name_plural': '攝影作品-專業形象照片',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pn_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn_ph_001', models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '攝影作品-孕婦寫真',
                'verbose_name_plural': '攝影作品-孕婦寫真',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Price_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_btn_001', models.CharField(default='', max_length=1000, verbose_name='選項名稱')),
                ('price_txt_001', ckeditor.fields.RichTextField(blank=True, default='輸入文字敘述', max_length=1000, null=True, verbose_name='內容')),
            ],
            options={
                'verbose_name': '婚紗單拍',
                'verbose_name_plural': '婚紗單拍',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Price_002',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_btn_002', models.CharField(default='按鈕名稱', max_length=1000, verbose_name='選項名稱')),
                ('price_txt_002', ckeditor.fields.RichTextField(blank=True, default='輸入文字敘述', max_length=1000, null=True, verbose_name='內容')),
            ],
            options={
                'verbose_name': '孕婦寫真',
                'verbose_name_plural': '孕婦寫真',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Price_003',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_btn_003', models.CharField(default='按鈕名稱', max_length=1000, verbose_name='選項名稱')),
                ('price_txt_003', ckeditor.fields.RichTextField(blank=True, default='輸入文字敘述', max_length=1000, null=True, verbose_name='內容')),
            ],
            options={
                'verbose_name': '同志寫真｜同性婚紗',
                'verbose_name_plural': '同志寫真｜同性婚紗',
            },
        ),
        migrations.CreateModel(
            name='Price_004',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_btn_004', models.CharField(default='按鈕名稱', max_length=1000, verbose_name='選項名稱')),
                ('price_txt_004', ckeditor.fields.RichTextField(blank=True, default='輸入文字敘述', max_length=1000, null=True, verbose_name='內容')),
            ],
            options={
                'verbose_name': '婚紗包套',
                'verbose_name_plural': '婚紗包套',
            },
        ),
        migrations.CreateModel(
            name='Pt_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_ph_001', models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '攝影作品-寵物婚紗',
                'verbose_name_plural': '攝影作品-寵物婚紗',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Service_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_ph_001', models.CharField(default='圖片連結', max_length=1000)),
            ],
            options={
                'verbose_name': '服務流程',
                'verbose_name_plural': '服務流程',
            },
        ),
        migrations.CreateModel(
            name='Sg_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_ph_001', models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '攝影作品-單身婚紗',
                'verbose_name_plural': '攝影作品-單身婚紗',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Studio_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_ph_001', models.CharField(default='', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '攝影棚圖片',
                'verbose_name_plural': '攝影棚圖片',
            },
        ),
        migrations.CreateModel(
            name='Wedding_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wedding_ph_001', models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '古裝婚紗',
                'verbose_name_plural': '古裝婚紗',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Wedding_02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wedding_02_ph_001', models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '景點婚紗',
                'verbose_name_plural': '景點婚紗',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Wedding_03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wedding_03_ph_001', models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '摩登婚紗',
                'verbose_name_plural': '摩登婚紗',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Wedding_04',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wedding_04_ph_001', models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '韓系婚紗',
                'verbose_name_plural': '韓系婚紗',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='wedding_form_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wed_001_name_w', models.CharField(default='', max_length=1000, verbose_name='新娘姓名')),
                ('wed_001_name_m', models.CharField(default='', max_length=1000, verbose_name='新郎姓名')),
                ('wed_001_phone_w', models.CharField(default='', max_length=1000, verbose_name='新娘電話')),
                ('wed_001_phone_m', models.CharField(default='', max_length=1000, verbose_name='新郎電話')),
                ('wed_001_email', models.CharField(default='', max_length=1000, verbose_name='信箱')),
                ('wed_001_address', models.CharField(default='', max_length=1000, verbose_name='地址')),
                ('wed_001_items_01', models.CharField(default='', max_length=1000, verbose_name='產品項目')),
                ('wed_001_items_02', models.CharField(default='', max_length=1000, verbose_name='預約套系')),
                ('wed_001_items_03', models.CharField(default='', max_length=1000, verbose_name='娘家冊/掌中本')),
                ('wed_001_items_04', models.CharField(default='', max_length=1000, verbose_name='放大商品')),
            ],
            options={
                'verbose_name': '婚紗表單',
                'verbose_name_plural': '婚紗表單',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='youtube_studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_yt_001', models.CharField(default='影片', max_length=1000, verbose_name='影片連結')),
                ('video_tit_001', models.CharField(default='標題', max_length=1000, verbose_name='影片標題')),
            ],
            options={
                'verbose_name': 'youtube影片',
                'verbose_name_plural': 'youtube影片',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(choices=[('tops', '衣服'), ('pants', '褲子'), ('shoes', '鞋子'), ('accessories', '配件'), ('maintenance', '保養品'), ('makeup', '化妝品')], max_length=20)),
                ('fromname', models.CharField(max_length=10)),
                ('arrivalname', models.CharField(max_length=50)),
                ('pd_number', models.CharField(max_length=10, null=True)),
                ('description', models.CharField(max_length=100)),
                ('finish', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now=True, null=True)),
                ('pd_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
