# Generated by Django 3.0 on 2020-05-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
