# Generated by Django 3.2.5 on 2023-03-31 08:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='at_001',
            options={'ordering': ['-id'], 'verbose_name': '海外專區', 'verbose_name_plural': '海外專區'},
        ),
        migrations.AlterField(
            model_name='at_001',
            name='at_con_001',
            field=ckeditor.fields.RichTextField(blank=True, default='海外內容', max_length=1000, null=True, verbose_name='海外內容'),
        ),
        migrations.AlterField(
            model_name='at_001',
            name='at_ph_001',
            field=models.CharField(default='海外圖照', max_length=1000, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='at_001',
            name='at_tit_001',
            field=models.CharField(default='標題', max_length=1000, verbose_name='標題'),
        ),
    ]
