# Generated by Django 3.2.5 on 2023-04-04 06:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20230331_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='at_001',
            name='at_con_001',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=100000, null=True, verbose_name='海外內容'),
        ),
        migrations.AlterField(
            model_name='at_001',
            name='at_ph_001',
            field=models.CharField(default='', max_length=1000, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='at_001',
            name='at_tit_001',
            field=models.CharField(default='', max_length=1000, verbose_name='標題'),
        ),
    ]
