# Generated by Django 3.2.5 on 2023-04-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20230404_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='at_001',
            name='at_in_tit_001',
            field=models.CharField(default='', max_length=1000, verbose_name='內文標題'),
        ),
        migrations.AlterField(
            model_name='at_001',
            name='at_ph_001',
            field=models.CharField(default='', max_length=1000, verbose_name='封面照'),
        ),
        migrations.AlterField(
            model_name='at_001',
            name='at_tit_001',
            field=models.CharField(default='', max_length=1000, verbose_name='大標題'),
        ),
    ]
