# Generated by Django 3.0 on 2020-06-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=10)),
                ('fromname', models.CharField(max_length=10)),
                ('arrivalname', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('finish', models.BooleanField(default=False)),
            ],
        ),
    ]
