# Generated by Django 3.0 on 2020-07-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
