# Generated by Django 3.2.5 on 2021-08-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20210805_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='pd_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
