# Generated by Django 3.2.5 on 2021-08-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20210806_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='items',
            field=models.CharField(choices=[('tops', '衣服'), ('pants', '褲子'), ('shoes', '鞋子'), ('accessories', '配件'), ('maintenance', '保養品'), ('makeup', '化妝品')], max_length=20),
        ),
    ]
