# Generated by Django 3.2.5 on 2021-08-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_alter_flight_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
