# Generated by Django 3.2.5 on 2021-08-10 10:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='pd_content',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='flight',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
