# Generated by Django 3.2.5 on 2021-08-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0025_alter_flight_pd_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_001', models.CharField(max_length=10)),
                ('mid_002', models.CharField(max_length=10)),
                ('mid_003', models.CharField(max_length=10)),
                ('mid_004', models.CharField(max_length=10)),
                ('mid_005', models.CharField(max_length=10)),
                ('mid_006', models.CharField(max_length=10)),
                ('mid_txt_001', models.CharField(max_length=50)),
                ('mid_txt_002', models.CharField(max_length=50)),
                ('mid_txt_003', models.CharField(max_length=50)),
                ('mid_txt_004', models.CharField(max_length=50)),
                ('mid_txt_005', models.CharField(max_length=50)),
                ('mid_txt_006', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
