# Generated by Django 3.2.5 on 2021-09-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_auto_20210908_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_ph_001', models.CharField(default='輸入圖片連結', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='studio_001',
            name='studio_ph_001',
            field=models.CharField(default='輸入圖片連結', max_length=1000),
        ),
    ]
