# Generated by Django 3.2.5 on 2021-09-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0030_auto_20210909_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_001',
            name='price_tit_001',
            field=models.CharField(default='標題名稱', max_length=1000),
        ),
    ]
