# Generated by Django 3.2.5 on 2021-09-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0031_price_001_price_tit_001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_001',
            name='price_tit_001',
        ),
    ]
