# Generated by Django 3.2.5 on 2021-09-23 08:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0033_auto_20210922_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_003',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_btn_003', models.CharField(default='按鈕名稱', max_length=1000)),
                ('price_txt_003', ckeditor.fields.RichTextField(blank=True, default='輸入文字敘述', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price_004',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_btn_004', models.CharField(default='按鈕名稱', max_length=1000)),
                ('price_txt_004', ckeditor.fields.RichTextField(blank=True, default='輸入文字敘述', max_length=1000, null=True)),
            ],
        ),
    ]
