# Generated by Django 3.2.5 on 2021-09-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0035_pn_001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cp_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_ph_001', models.CharField(default='圖片連結', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pf_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_ph_001', models.CharField(default='圖片連結', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pt_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_ph_001', models.CharField(default='圖片連結', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sg_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_ph_001', models.CharField(default='圖片連結', max_length=1000)),
            ],
        ),
    ]
