# Generated by Django 3.2.5 on 2021-10-01 12:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0036_cp_001_pf_001_pt_001_sg_001'),
    ]

    operations = [
        migrations.CreateModel(
            name='at_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_tit_001', models.CharField(default='標題', max_length=1000)),
                ('at_con_001', ckeditor.fields.RichTextField(blank=True, default='活動內容', max_length=1000, null=True)),
            ],
        ),
    ]
