# Generated by Django 3.2.5 on 2021-10-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0037_at_001'),
    ]

    operations = [
        migrations.AddField(
            model_name='at_001',
            name='at_ph_001',
            field=models.CharField(default='活動主照', max_length=1000),
        ),
    ]
