# Generated by Django 3.2.5 on 2021-10-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0038_at_001_at_ph_001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wedding_ph_001', models.CharField(default='圖片連結', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='at_001',
            name='at_ph_001',
            field=models.CharField(default='活動圖照', max_length=1000),
        ),
    ]
