# Generated by Django 3.2.5 on 2021-10-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0039_auto_20211014_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding_02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wedding_02_ph_001', models.CharField(default='圖片連結', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Wedding_03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wedding_03_ph_001', models.CharField(default='圖片連結', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Wedding_04',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wedding_04_ph_001', models.CharField(default='圖片連結', max_length=1000)),
            ],
        ),
    ]
