# Generated by Django 3.2.5 on 2021-11-23 08:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0040_wedding_02_wedding_03_wedding_04'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='at_001',
            options={'verbose_name': '活動專區', 'verbose_name_plural': '活動專區'},
        ),
        migrations.AlterModelOptions(
            name='cp_001',
            options={'verbose_name': '攝影作品-情侶寫真', 'verbose_name_plural': '攝影作品-情侶寫真'},
        ),
        migrations.AlterModelOptions(
            name='index_001',
            options={'verbose_name': '首頁', 'verbose_name_plural': '首頁'},
        ),
        migrations.AlterModelOptions(
            name='pf_001',
            options={'verbose_name': '攝影作品-專業形象照片', 'verbose_name_plural': '攝影作品-專業形象照片'},
        ),
        migrations.AlterModelOptions(
            name='pn_001',
            options={'verbose_name': '攝影作品-孕婦寫真', 'verbose_name_plural': '攝影作品-孕婦寫真'},
        ),
        migrations.AlterModelOptions(
            name='price_001',
            options={'verbose_name': '婚紗單拍', 'verbose_name_plural': '婚紗單拍'},
        ),
        migrations.AlterModelOptions(
            name='price_002',
            options={'verbose_name': '孕婦寫真', 'verbose_name_plural': '孕婦寫真'},
        ),
        migrations.AlterModelOptions(
            name='price_003',
            options={'verbose_name': '同志寫真｜同性婚紗', 'verbose_name_plural': '同志寫真｜同性婚紗'},
        ),
        migrations.AlterModelOptions(
            name='price_004',
            options={'verbose_name': '婚紗包套', 'verbose_name_plural': '婚紗包套'},
        ),
        migrations.AlterModelOptions(
            name='pt_001',
            options={'verbose_name': '攝影作品-寵物婚紗', 'verbose_name_plural': '攝影作品-寵物婚紗'},
        ),
        migrations.AlterModelOptions(
            name='sg_001',
            options={'verbose_name': '攝影作品-單身婚紗', 'verbose_name_plural': '攝影作品-單身婚紗'},
        ),
        migrations.AlterModelOptions(
            name='studio_001',
            options={'verbose_name': '攝影棚圖片', 'verbose_name_plural': '攝影棚圖片'},
        ),
        migrations.AlterModelOptions(
            name='wedding_01',
            options={'verbose_name': '古裝婚紗', 'verbose_name_plural': '古裝婚紗'},
        ),
        migrations.AlterModelOptions(
            name='wedding_02',
            options={'verbose_name': '景點婚紗', 'verbose_name_plural': '景點婚紗'},
        ),
        migrations.AlterModelOptions(
            name='wedding_03',
            options={'verbose_name': '摩登婚紗', 'verbose_name_plural': '摩登婚紗'},
        ),
        migrations.AlterModelOptions(
            name='wedding_04',
            options={'verbose_name': '韓系婚紗', 'verbose_name_plural': '韓系婚紗'},
        ),
        migrations.AlterField(
            model_name='at_001',
            name='at_con_001',
            field=ckeditor.fields.RichTextField(blank=True, default='活動內容', max_length=1000, null=True, verbose_name='活動內容'),
        ),
        migrations.AlterField(
            model_name='at_001',
            name='at_ph_001',
            field=models.CharField(default='活動圖照', max_length=1000, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='at_001',
            name='at_tit_001',
            field=models.CharField(default='標題', max_length=1000, verbose_name='活動名稱'),
        ),
        migrations.AlterField(
            model_name='cp_001',
            name='cp_ph_001',
            field=models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_001',
            field=models.CharField(max_length=10, verbose_name='標題名稱'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_002',
            field=models.CharField(max_length=10, verbose_name='標題名稱'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_003',
            field=models.CharField(max_length=10, verbose_name='標題名稱'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_004',
            field=models.CharField(max_length=10, verbose_name='標題名稱'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_005',
            field=models.CharField(max_length=10, verbose_name='標題名稱'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_006',
            field=models.CharField(max_length=10, verbose_name='標題名稱'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_ph_001',
            field=models.CharField(max_length=1000, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_ph_002',
            field=models.CharField(max_length=1000, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_ph_003',
            field=models.CharField(max_length=1000, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_ph_004',
            field=models.CharField(max_length=1000, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_ph_005',
            field=models.CharField(max_length=1000, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_ph_006',
            field=models.CharField(max_length=1000, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_txt_001',
            field=models.TextField(max_length=100, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_txt_002',
            field=models.TextField(max_length=100, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_txt_003',
            field=models.TextField(max_length=100, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_txt_004',
            field=models.TextField(max_length=100, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_txt_005',
            field=models.TextField(max_length=100, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='index_001',
            name='mid_txt_006',
            field=models.TextField(max_length=100, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='pf_001',
            name='pf_ph_001',
            field=models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='pn_001',
            name='pn_ph_001',
            field=models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='price_001',
            name='price_btn_001',
            field=models.CharField(default='', max_length=1000, verbose_name='選項名稱'),
        ),
        migrations.AlterField(
            model_name='price_001',
            name='price_txt_001',
            field=ckeditor.fields.RichTextField(blank=True, default='輸入文字敘述', max_length=1000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='price_002',
            name='price_btn_002',
            field=models.CharField(default='按鈕名稱', max_length=1000, verbose_name='選項名稱'),
        ),
        migrations.AlterField(
            model_name='price_002',
            name='price_txt_002',
            field=ckeditor.fields.RichTextField(blank=True, default='輸入文字敘述', max_length=1000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='price_003',
            name='price_btn_003',
            field=models.CharField(default='按鈕名稱', max_length=1000, verbose_name='選項名稱'),
        ),
        migrations.AlterField(
            model_name='price_003',
            name='price_txt_003',
            field=ckeditor.fields.RichTextField(blank=True, default='輸入文字敘述', max_length=1000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='price_004',
            name='price_btn_004',
            field=models.CharField(default='按鈕名稱', max_length=1000, verbose_name='選項名稱'),
        ),
        migrations.AlterField(
            model_name='price_004',
            name='price_txt_004',
            field=ckeditor.fields.RichTextField(blank=True, default='輸入文字敘述', max_length=1000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='pt_001',
            name='pt_ph_001',
            field=models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='sg_001',
            name='sg_ph_001',
            field=models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='studio_001',
            name='studio_ph_001',
            field=models.CharField(default='', max_length=1000, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='wedding_01',
            name='Wedding_ph_001',
            field=models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='wedding_02',
            name='Wedding_02_ph_001',
            field=models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='wedding_03',
            name='Wedding_03_ph_001',
            field=models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='wedding_04',
            name='Wedding_04_ph_001',
            field=models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結'),
        ),
    ]
