# Generated by Django 3.2.5 on 2022-05-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0041_auto_20211123_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service_001',
            options={'verbose_name': '服務流程', 'verbose_name_plural': '服務流程'},
        ),
    ]
