# Generated by Django 3.2.5 on 2022-07-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0042_alter_service_001_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_001',
            name='mid_ph_010',
            field=models.CharField(max_length=1000, null=True, verbose_name='左直'),
        ),
        migrations.AddField(
            model_name='index_001',
            name='mid_ph_011',
            field=models.CharField(max_length=1000, null=True, verbose_name='右上'),
        ),
        migrations.AddField(
            model_name='index_001',
            name='mid_ph_012',
            field=models.CharField(max_length=1000, null=True, verbose_name='右下'),
        ),
    ]
