# Generated by Django 3.2.5 on 2022-07-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0043_auto_20220707_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='castle_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castle_ph_001', models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '古堡婚紗',
                'verbose_name_plural': '古堡婚紗',
            },
        ),
        migrations.CreateModel(
            name='location_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_ph_001', models.CharField(default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '拍攝景點',
                'verbose_name_plural': '拍攝景點',
            },
        ),
    ]
