# Generated by Django 3.2.5 on 2022-11-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0044_castle_01_location_01'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio_002',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '攝影棚圖片',
                'verbose_name_plural': '攝影棚圖片',
            },
        ),
    ]
