# Generated by Django 3.2.5 on 2022-11-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0045_studio_002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studio_002',
            options={'verbose_name': 'youtube門市', 'verbose_name_plural': 'youtube門市'},
        ),
        migrations.AddField(
            model_name='studio_002',
            name='studio_yt',
            field=models.CharField(default='', max_length=1000, verbose_name='影片連結'),
        ),
        migrations.AddField(
            model_name='studio_002',
            name='studio_yt_tit',
            field=models.CharField(default='', max_length=1000, verbose_name='選項名稱'),
        ),
    ]
