# Generated by Django 3.2.5 on 2022-11-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0046_auto_20221111_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studio_002',
            options={'verbose_name': '門市攝影棚', 'verbose_name_plural': '門市/攝影棚'},
        ),
        migrations.AlterField(
            model_name='studio_002',
            name='studio_yt',
            field=models.CharField(default='', max_length=1000, verbose_name='嵌入youtube連結'),
        ),
    ]
