# Generated by Django 3.2.5 on 2022-11-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0047_auto_20221111_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='youtube_studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_yt_001', models.CharField(default='影片', max_length=1000, verbose_name='影片連結')),
            ],
            options={
                'verbose_name': 'youtube影片',
                'verbose_name_plural': 'youtube影片',
            },
        ),
        migrations.DeleteModel(
            name='Studio_002',
        ),
    ]
