# Generated by Django 3.2.5 on 2022-11-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0048_auto_20221115_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_studio',
            name='video_tit_001',
            field=models.CharField(default='標題', max_length=1000, verbose_name='影片標題'),
        ),
    ]
