# Generated by Django 3.2.5 on 2022-12-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0049_youtube_studio_video_tit_001'),
    ]

    operations = [
        migrations.CreateModel(
            name='family_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam_001', models.CharField(default='', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '全家福',
                'verbose_name_plural': '全家福',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='at_001',
            options={'ordering': ['-id'], 'verbose_name': '活動專區', 'verbose_name_plural': '活動專區'},
        ),
        migrations.AlterModelOptions(
            name='castle_01',
            options={'ordering': ['-id'], 'verbose_name': '古堡婚紗', 'verbose_name_plural': '古堡婚紗'},
        ),
        migrations.AlterModelOptions(
            name='cp_001',
            options={'ordering': ['-id'], 'verbose_name': '攝影作品-情侶寫真', 'verbose_name_plural': '攝影作品-情侶寫真'},
        ),
        migrations.AlterModelOptions(
            name='pf_001',
            options={'ordering': ['-id'], 'verbose_name': '攝影作品-專業形象照片', 'verbose_name_plural': '攝影作品-專業形象照片'},
        ),
        migrations.AlterModelOptions(
            name='pn_001',
            options={'ordering': ['-id'], 'verbose_name': '攝影作品-孕婦寫真', 'verbose_name_plural': '攝影作品-孕婦寫真'},
        ),
        migrations.AlterModelOptions(
            name='price_001',
            options={'ordering': ['-id'], 'verbose_name': '婚紗單拍', 'verbose_name_plural': '婚紗單拍'},
        ),
        migrations.AlterModelOptions(
            name='price_002',
            options={'ordering': ['-id'], 'verbose_name': '孕婦寫真', 'verbose_name_plural': '孕婦寫真'},
        ),
        migrations.AlterModelOptions(
            name='pt_001',
            options={'ordering': ['-id'], 'verbose_name': '攝影作品-寵物婚紗', 'verbose_name_plural': '攝影作品-寵物婚紗'},
        ),
        migrations.AlterModelOptions(
            name='sg_001',
            options={'ordering': ['-id'], 'verbose_name': '攝影作品-單身婚紗', 'verbose_name_plural': '攝影作品-單身婚紗'},
        ),
        migrations.AlterModelOptions(
            name='wedding_01',
            options={'ordering': ['-id'], 'verbose_name': '古裝婚紗', 'verbose_name_plural': '古裝婚紗'},
        ),
        migrations.AlterModelOptions(
            name='wedding_02',
            options={'ordering': ['-id'], 'verbose_name': '景點婚紗', 'verbose_name_plural': '景點婚紗'},
        ),
        migrations.AlterModelOptions(
            name='wedding_03',
            options={'ordering': ['-id'], 'verbose_name': '摩登婚紗', 'verbose_name_plural': '摩登婚紗'},
        ),
        migrations.AlterModelOptions(
            name='wedding_04',
            options={'ordering': ['-id'], 'verbose_name': '韓系婚紗', 'verbose_name_plural': '韓系婚紗'},
        ),
    ]
