# Generated by Django 3.2.5 on 2023-01-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0050_auto_20221230_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='wedding_form_001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wed_001_name_w', models.CharField(default='', max_length=1000, verbose_name='新郎姓名')),
                ('wed_001_name_m', models.CharField(default='', max_length=1000, verbose_name='新郎姓名')),
            ],
            options={
                'verbose_name': '婚紗表單',
                'verbose_name_plural': '婚紗表單',
                'ordering': ['-id'],
            },
        ),
    ]
