# Generated by Django 3.2.5 on 2021-11-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shotdogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_ph_001', models.CharField(blank=True, max_length=1000, verbose_name='輪播1')),
                ('mid_ph_002', models.CharField(blank=True, max_length=1000, verbose_name='輪播2')),
                ('mid_ph_003', models.CharField(blank=True, max_length=1000, verbose_name='輪播3')),
            ],
            options={
                'verbose_name': '攝狗狗-首頁',
                'verbose_name_plural': '攝狗狗-首頁',
            },
        ),
    ]
