# Generated by Django 3.2.5 on 2021-11-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shotdogs', '0002_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price_ph_001', models.CharField(blank=True, max_length=1000, verbose_name='標題照片')),
                ('Price_txt_001', models.CharField(blank=True, max_length=1000, verbose_name='標題')),
                ('Price_con_001', models.CharField(blank=True, max_length=1000, verbose_name='內容')),
            ],
            options={
                'verbose_name': '攝狗狗-套裝',
                'verbose_name_plural': '攝狗狗-套裝',
            },
        ),
    ]
