# Generated by Django 3.2.5 on 2021-12-02 07:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shotdogs', '0003_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atc_tit_001', models.CharField(blank=True, max_length=1000, verbose_name='文章標題')),
                ('atc_ph_001', models.CharField(blank=True, max_length=1000, verbose_name='文張照片')),
                ('atc_con_001', ckeditor.fields.RichTextField(blank=True, default='輸入', max_length=2000, null=True, verbose_name='內容')),
            ],
            options={
                'verbose_name': '攝狗狗-文章',
                'verbose_name_plural': '攝狗狗-文章',
            },
        ),
        migrations.AlterField(
            model_name='price',
            name='Price_con_001',
            field=ckeditor.fields.RichTextField(blank=True, default='輸入', max_length=2000, null=True, verbose_name='內容'),
        ),
    ]
