# Generated by Django 3.2.5 on 2022-04-01 12:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shotdogs', '0004_auto_20211202_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='atc_con_001',
            field=ckeditor.fields.RichTextField(blank=True, default='輸入', max_length=10000, null=True, verbose_name='內容'),
        ),
    ]
