# Generated by Django 3.2.5 on 2023-03-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vh_big_cpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vh_big_cpl_001', models.CharField(blank=True, default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '手工-情侶寫真',
                'verbose_name_plural': '手工-情侶寫真',
            },
        ),
        migrations.CreateModel(
            name='vh_big_frds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vh_big_frds_001', models.CharField(blank=True, default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '手工-閨蜜寫真',
                'verbose_name_plural': '手工-閨蜜寫真',
            },
        ),
        migrations.CreateModel(
            name='vh_big_single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vh_big_single_001', models.CharField(blank=True, default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '手工-個人寫真',
                'verbose_name_plural': '手工-個人寫真',
            },
        ),
        migrations.CreateModel(
            name='vh_index_001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vh_banner_001', models.CharField(blank=True, max_length=1000, null=True, verbose_name='置頂大圖')),
                ('vh_top_001', models.CharField(blank=True, max_length=1000, null=True, verbose_name='左')),
                ('vh_top_002', models.CharField(blank=True, max_length=1000, null=True, verbose_name='右上')),
                ('vh_top_003', models.CharField(blank=True, max_length=1000, null=True, verbose_name='右下')),
                ('vh_mid_001', models.CharField(blank=True, max_length=1000, verbose_name='標題名稱')),
                ('vh_mid_ph_001', models.CharField(blank=True, max_length=1000, null=True, verbose_name='照片連結')),
                ('vh_mid_txt_001', models.TextField(blank=True, max_length=1000, verbose_name='內容')),
                ('vh_mid_002', models.CharField(blank=True, max_length=1000, verbose_name='標題名稱')),
                ('vh_mid_ph_002', models.CharField(blank=True, max_length=1000, null=True, verbose_name='照片連結')),
                ('vh_mid_txt_002', models.TextField(blank=True, max_length=1000, verbose_name='內容')),
                ('vh_mid_003', models.CharField(blank=True, max_length=1000, verbose_name='標題名稱')),
                ('vh_mid_ph_003', models.CharField(blank=True, max_length=1000, null=True, verbose_name='照片連結')),
                ('vh_mid_txt_003', models.TextField(blank=True, max_length=1000, verbose_name='內容')),
                ('vh_mid_004', models.CharField(blank=True, max_length=1000, verbose_name='標題名稱')),
                ('vh_mid_txt_004', models.TextField(blank=True, max_length=1000, verbose_name='內容')),
                ('vh_mid_ph_004', models.CharField(blank=True, max_length=1000, null=True, verbose_name='照片連結')),
                ('vh_mid_005', models.CharField(blank=True, max_length=1000, verbose_name='標題名稱')),
                ('vh_mid_txt_005', models.TextField(blank=True, max_length=1000, verbose_name='內容')),
                ('vh_mid_ph_005', models.CharField(blank=True, max_length=1000, null=True, verbose_name='照片連結')),
                ('vh_mid_006', models.CharField(blank=True, max_length=1000, verbose_name='標題名稱')),
                ('vh_mid_txt_006', models.TextField(blank=True, max_length=1000, verbose_name='內容')),
                ('vh_mid_ph_006', models.CharField(blank=True, max_length=1000, null=True, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '手工-首頁',
                'verbose_name_plural': '手工-首頁',
            },
        ),
        migrations.CreateModel(
            name='vh_studio_001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vh_studio_001', models.CharField(blank=True, default='', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '手工-攝影棚圖片',
                'verbose_name_plural': '手工-攝影棚圖片',
            },
        ),
        migrations.CreateModel(
            name='vh_style_001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vh_style_st_001', models.CharField(blank=True, default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '手工-自然景致',
                'verbose_name_plural': '手工-自然景致',
            },
        ),
        migrations.CreateModel(
            name='vh_style_002',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vh_style_st_002', models.CharField(blank=True, default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '手工-幸福街角',
                'verbose_name_plural': '手工-幸福街角',
            },
        ),
        migrations.CreateModel(
            name='vh_style_003',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vh_style_st_003', models.CharField(blank=True, default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '手工-風格內景',
                'verbose_name_plural': '手工-風格內景',
            },
        ),
        migrations.CreateModel(
            name='vh_style_004',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vh_style_st_004', models.CharField(blank=True, default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '手工-唯美光芒',
                'verbose_name_plural': '手工-唯美光芒',
            },
        ),
        migrations.CreateModel(
            name='vh_style_005',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vh_style_st_005', models.CharField(blank=True, default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '手工-甜膩俏皮',
                'verbose_name_plural': '手工-甜膩俏皮',
            },
        ),
        migrations.CreateModel(
            name='vh_style_006',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vh_style_st_006', models.CharField(blank=True, default='圖片連結', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '手工-意境劇情',
                'verbose_name_plural': '手工-意境劇情',
            },
        ),
    ]
