# Generated by Django 3.2.5 on 2022-04-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veronahuang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vh_big_cpl',
            options={'verbose_name': '手工-情侶寫真', 'verbose_name_plural': '手工-情侶寫真'},
        ),
        migrations.AlterModelOptions(
            name='vh_big_frds',
            options={'verbose_name': '手工-閨蜜寫真', 'verbose_name_plural': '手工-閨蜜寫真'},
        ),
        migrations.AlterModelOptions(
            name='vh_big_single',
            options={'verbose_name': '手工-個人寫真', 'verbose_name_plural': '手工-個人寫真'},
        ),
        migrations.AlterModelOptions(
            name='vh_style_001',
            options={'verbose_name': '手工-自然景致', 'verbose_name_plural': '手工-自然景致'},
        ),
        migrations.AlterModelOptions(
            name='vh_style_002',
            options={'verbose_name': '手工-幸福街角', 'verbose_name_plural': '手工-幸福街角'},
        ),
        migrations.AlterModelOptions(
            name='vh_style_003',
            options={'verbose_name': '手工-風格內景', 'verbose_name_plural': '手工-風格內景'},
        ),
        migrations.AlterModelOptions(
            name='vh_style_004',
            options={'verbose_name': '手工-唯美光芒', 'verbose_name_plural': '手工-唯美光芒'},
        ),
        migrations.AlterModelOptions(
            name='vh_style_005',
            options={'verbose_name': '手工-甜膩俏皮', 'verbose_name_plural': '手工-甜膩俏皮'},
        ),
        migrations.AlterModelOptions(
            name='vh_style_006',
            options={'verbose_name': '手工-意境劇情', 'verbose_name_plural': '手工-意境劇情'},
        ),
    ]
