# Generated by Django 3.2.5 on 2022-04-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veronahuang', '0002_auto_20220401_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='vh_index_001',
            name='vh_banner_001',
            field=models.CharField(max_length=10, null=True, verbose_name='置頂大圖'),
        ),
        migrations.AddField(
            model_name='vh_index_001',
            name='vh_top_001',
            field=models.CharField(max_length=10, null=True, verbose_name='左'),
        ),
        migrations.AddField(
            model_name='vh_index_001',
            name='vh_top_002',
            field=models.CharField(max_length=10, null=True, verbose_name='右上'),
        ),
        migrations.AddField(
            model_name='vh_index_001',
            name='vh_top_003',
            field=models.CharField(max_length=10, null=True, verbose_name='右下'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_ph_001',
            field=models.CharField(max_length=10, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_ph_002',
            field=models.CharField(max_length=10, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_ph_003',
            field=models.CharField(max_length=10, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_ph_004',
            field=models.CharField(max_length=10, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_ph_005',
            field=models.CharField(max_length=10, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_ph_006',
            field=models.CharField(max_length=10, null=True, verbose_name='照片連結'),
        ),
    ]
