# Generated by Django 3.2.5 on 2022-04-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veronahuang', '0003_auto_20220407_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_banner_001',
            field=models.CharField(max_length=1000, null=True, verbose_name='置頂大圖'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_001',
            field=models.CharField(max_length=1000, verbose_name='標題名稱'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_002',
            field=models.CharField(max_length=1000, verbose_name='標題名稱'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_003',
            field=models.CharField(max_length=1000, verbose_name='標題名稱'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_004',
            field=models.CharField(max_length=1000, verbose_name='標題名稱'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_005',
            field=models.CharField(max_length=1000, verbose_name='標題名稱'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_006',
            field=models.CharField(max_length=1000, verbose_name='標題名稱'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_ph_001',
            field=models.CharField(max_length=1000, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_ph_002',
            field=models.CharField(max_length=1000, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_ph_003',
            field=models.CharField(max_length=1000, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_ph_004',
            field=models.CharField(max_length=1000, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_ph_005',
            field=models.CharField(max_length=1000, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_ph_006',
            field=models.CharField(max_length=1000, null=True, verbose_name='照片連結'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_txt_001',
            field=models.TextField(max_length=1000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_txt_002',
            field=models.TextField(max_length=1000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_txt_003',
            field=models.TextField(max_length=1000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_txt_004',
            field=models.TextField(max_length=1000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_txt_005',
            field=models.TextField(max_length=1000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_mid_txt_006',
            field=models.TextField(max_length=1000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_top_001',
            field=models.CharField(max_length=1000, null=True, verbose_name='左'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_top_002',
            field=models.CharField(max_length=1000, null=True, verbose_name='右上'),
        ),
        migrations.AlterField(
            model_name='vh_index_001',
            name='vh_top_003',
            field=models.CharField(max_length=1000, null=True, verbose_name='右下'),
        ),
    ]
