# Generated by Django 3.2.5 on 2023-02-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kids_ph_nb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kids_ph_nb_001', models.CharField(default='', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '新生兒',
                'verbose_name_plural': '新生兒',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='kids_ph_oyoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kids_ph_oyoc_001', models.CharField(default='', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '兒童抓洲',
                'verbose_name_plural': '兒童抓洲',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='kids_ph_pw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kids_ph_pw_001', models.CharField(default='', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '孕婦婚紗',
                'verbose_name_plural': '孕婦婚紗',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='kids_ph_salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kids_ph_salon_001', models.CharField(default='', max_length=1000, verbose_name='照片連結')),
            ],
            options={
                'verbose_name': '兒童情境',
                'verbose_name_plural': '兒童情境',
                'ordering': ['-id'],
            },
        ),
    ]
