# Generated by Django 3.2.5 on 2023-03-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_kids_ph_nb_kids_ph_oyoc_kids_ph_pw_kids_ph_salon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kid_index',
            options={'verbose_name': '兒童首頁', 'verbose_name_plural': '兒童首頁'},
        ),
        migrations.AlterModelOptions(
            name='kids_ph_oyoc',
            options={'ordering': ['-id'], 'verbose_name': '兒童抓周', 'verbose_name_plural': '兒童抓周'},
        ),
    ]
